name: Deploy ebook-web to EC2

on:
  push:
    branches: [ cicd ]
    paths:
      - 'ebook-web/**'
      - 'ebook-domain/**'
  pull_request:
    branches: [ cicd ]
    paths:
      - 'ebook-web/**'
      - 'ebook-domain/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build ebook-web with Gradle
        run: ./gradlew :ebook-web:build

      - name: Build Docker image
        run: |
          cd ebook-web
          docker build -t ebook-web .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            docker stop ebook-web || true
            docker rm ebook-web || true
            docker pull ebook-web:latest
            docker run -d --name ebook-web -p 8080:8080 ebook-web:latest
          '