name: 'Chromatic Deployment'

on:
  push:
    branches:
      - feature/sonarcloud-chromatic-setup

jobs:
  chromatic-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          sparse-checkout: |
            ./fe

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"

      - name: Install dependency
        run: |
          cd ./fe
          npm install

      - name: Run Chromatic
        run: |
          cd ./fe
          npx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --token=${{ secrets.GITHUB_TOKEN }}