name: 'Chromatic Deployment'

on:
  push:
    branches:
      - feature/sonarcloud-chromatic-setup

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn
        working-directory: ./fe
      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}  
        working-directory: ./fe
