name: Deploy Web Application

on:
  push:
    branches: [ dev-be ]
    paths:
      - 'be/**'
      - '.github/workflows/deploy-web.yml'
  pull_request:
    branches: [ dev-be ]
    paths:
      - 'be/**'
      - '.github/workflows/deploy-web.yml'
  workflow_dispatch:

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/ebook-web:${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle

      - name: Build ebook-web with Gradle
        working-directory: be/ebook-search
        run: |
          chmod +x ./gradlew
          ./gradlew :ebook-web:build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: be/ebook-search/ebook-web
          push: true
          tags: ${{ env.DOCKER_IMAGE }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}" > .env
            echo "GITHUB_SHA=${{ github.sha }}" >> .env
            echo "EC2_USERNAME=${{ secrets.EC2_USERNAME }}" >> .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            docker-compose pull
            docker-compose up -d