name: SonarCloud Scan

on:
  push:
    branches:
      - feat/sonar_setup
  pull_request:
    branches:
      - feat/sonar_setup

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'

      - name: Install dependencies
        working-directory: fe
        run: npm install

      - name: Run tests (Frontend)
        working-directory: fe
        run: npm run test:ci

      - name: SonarCloud Scan
        working-directory: fe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        run: |
          npx sonarqube-scanner \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.sources=src \
            -Dsonar.tests=src/tests \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=$SONAR_TOKEN
